# Generated by Django 4.1 on 2022-08-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('nome', models.CharField(max_length=150)),
                ('escola', models.CharField(max_length=250)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
