# Generated by Django 4.1 on 2022-08-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crianca_alter_usuario_cpf_alter_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='crianca',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='core.escola'),
        ),
    ]
